### ISSUE TITLE
Regarding certain errors found when running full audit run

### ISSUE THREAD

**Issue by Kedy1ykh** [ansible-lockdown/RHEL8-CIS-Audit#41]
Hi dev team,

I have noticed some of the missing rules in json report and did a backtrack to try to analyse the reason behind the missing rules. 
Some of the missing rules were cause by errors generated from goss validation.

Attached some of my findings and hope to hear more from you.

[cis_2.3.1_6.yml.txt](https://github.com/ansible-lockdown/RHEL8-CIS-Audit/files/9448944/cis_2.3.1_6.yml.txt)
[Actinum_RHEL8_CIS_AUDIT_git_diff.txt](https://github.com/ansible-lockdown/RHEL8-CIS-Audit/files/9448932/Actinum_RHEL8_CIS_AUDIT_git_diff.txt)
[Actinum_RHEL8_CIS_AUDIT_git_status.txt](https://github.com/ansible-lockdown/RHEL8-CIS-Audit/files/9448933/Actinum_RHEL8_CIS_AUDIT_git_status.txt)

**Comment by uk-bolly** [comment]
Hi @Kedy1ykh 

There is some great catches there and some brilliant work, thank you very much for the details. Did you want to open a pull request to merge into devel for your local branch and we can test and adopt these as soon as possible.
Please note.  These do need to be gpg signed and signed-off
That way you receive the credit for all your work by merging into the repo. 
Or i can look to adopt these and mark as credit in the new PR?


best regards and thank you again

uk-bolly

**Comment by Kedy1ykh** [comment]
Hi https://github.com/uk-bolly 

Thanks for the response, i will try to merge it to devel branch today.

**Comment by uk-bolly** [comment]
This has now been merged.
