### ISSUE TITLE
Duplicate checks

### ISSUE THREAD

**Issue by sysop200** [ansible-lockdown/RHEL8-CIS-Audit#55]
I found duplicate checks in the sections. I do not understand why? Version goss 0.4.3 immediately speaks about this.
Example, please check
section_3/cis_3.3/cis_3.3.7.yml
check duplicated net.ip4.conf.all.rp_filter
And this problem exists in all sections

**Comment by uk-bolly** [comment]
hi @sysop200 

Thank you again for raising this issue.
These should all be merged now. I will close this issue, please feel free to reopen if this is still an issue.

many thanks

uk-bolly
