### ISSUE TITLE
Syntax error on run_audit.sh

### ISSUE THREAD

**Issue by cpeetersburg** [ansible-lockdown/RHEL8-CIS-Audit#58]
**Describe the Issue**
When running `run_audit.sh`, you get the following error:
```bash
tr: missing operand after ‘[:lower:]’
Two strings must be given when translating.
Try 'tr --help' for more information.
```

**Expected Behavior**
This error shouldn't be thrown. This is clearly a syntax error in the script.

**Actual Behavior**
You get a syntax error

**Control(s) Affected**
- run_audit.sh

**Environment (please complete the following information):**

- goss version: 0.4.2
- OS version: openSUSE Tumbleweed on WSL
- Additional Details:

**Additional Notes**
Testing the code on my WSL sandbox before launching it in the actual environment

**Possible Solution**
On line 86 the following possible amendments can be made:
- `os_vendor="$(hostnamectl | grep Oper | cut -d: -f2 | awk '{print $1}' | tr '[:upper:]' '[:lower:]')"`
- `os_vendor="$(hostnamectl | grep Oper | cut -d: -f2 | awk '{print tolower($1)}')"`

**Comment by uk-bolly** [comment]
hi @cpeetersburg 

Thank you so much for the feedback and subsequent PR. This is indeed a great catch. I have feedback on the PR, very happy to take it but unfortunately it is not GPG signed. If you are able to get it signed will merge asap.

Many thanks once again

uk-bolly

**Comment by cpeetersburg** [comment]
Sorry for not signing. Should be okay now.

**Comment by uk-bolly** [comment]
hi @cpeetersburg 

Thank you again for raising this issue and PRs, I believe this is now all resolved and merged, i will therefore close this issue. Feel free to reopen if this is not the case.

many thanks

uk-bolly
