### ISSUE TITLE
Error when auditing

### ISSUE THREAD

**Issue by txsastre** [ansible-lockdown/RHEL8-CIS-Audit#68]
**Describe the Issue**
the playbook stops when trying to upload / unpack the RHEL8-CIS-Audit.tar.gz

```
ASK [/home/hal/ansible/hardening/RHEL8-CIS : Pre Audit Setup | Copy ansible default vars values to test audit] ******************************
fatal: [SRV3-OL8]: FAILED! => {"changed": false, "checksum": "9d6da5501987f6eec6dbe7082540601736830a17", "msg": "Destination directory /opt/RHEL8-CIS-Audit/vars does not exist"}
```

**Expected Behavior**
upload it to the path I modified the variable with a file, so as I can see it's hardcoded.

**Actual Behavior**
it stops, and does not do the audit.

**Control(s) Affected**
What controls are being affected by the issue
Relevant files associated.

**Environment (please complete the following information):**

- goss version: 0.4.4
- OS version: Debian 12 (Ansible controller) - Rocky Linux 8 the remote one.
- Additional Details:

**Additional Notes**
I think we already talked about that in Discord when we were tuning the UBUNTU-22-CIS (it had the same problems)

**Possible Solution**
As far as I see the problem is in the remediate file, and the solution should be the same that used in Ubuntu-22-cis-Audit

**Comment by uk-bolly** [comment]
This is resolved after discussions in discord.

thanks 

uk-bolly
